# a hardcoded list containing the U.S. state values

STATES = [
    'Massachusetts',
    'Connecticut',
    'New Hampshire',
    'Vermont',
    'New York',
    'Rhode Island',
    'Maine',
    'New Jersey',
    'Pennsylvania',
    'Delaware',
    'West Virginia',
    'Ohio',
    'Maryland',
    'Virginia',
    'Colorado',
    'North Carolina',
    'Kentucky',
    'Tennessee',
    'South Carolina',
    'Georgia',
    'Alabama',
    'Florida',
    'Mississippi',
    'Missouri',
    'Arkansas',
    'Louisiana',
    'Indiana',
    'Illinois',
    'Michigan',
    'Wisconsin',
    'Iowa',
    'Minnesota',
    'South Dakota',
    'Nebraska',
    'North Dakota',
    'Montana',
    'Idaho',
    'Kansas',
    'Oklahoma',
    'Wyoming',
    'Texas',
    'New Mexico',
    'Utah',
    'Washington',
    'Oregon',
    'Nevada',
    'Arizona',
    'California',
    'Hawaii']
